name: passport

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: passport-app
    env_file:
      - .env
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - passport-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: passport-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-passport}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - passport-network

networks:
  passport-network:
    driver: bridge

volumes:
  postgres-data:
